import { getUnitPixelArt } from "../code/pixelArt.js";

// 单位图片：优先本地图；否则使用程序生成的像素画占位
function unitImage(id, icon, tint = "#7fc7ff") {
  const base = typeof window !== "undefined" && window.__BASE__ ? window.__BASE__ : "";
  if (base) return `${base}assets/units/${id}.png`;
  return getUnitPixelArt(id, tint) || `https://placehold.co/80x80/1a2a4a/7fc7ff?text=${encodeURIComponent(icon)}`;
}

export const UNIT_CONFIG = [
  {
    id: "u_guard",
    name: "铁卫",
    icon: "🛡️",
    sprite: "🛡️",
    image: unitImage("u_guard", "🛡️", "#6ea9ff"),
    tint: "#6ea9ff",
    tier: 1,
    role: "frontline",
    hp: 120,
    atk: 14,
    trait: ["sentinel", "human"],
  },
  {
    id: "u_archer",
    name: "巡林射手",
    icon: "🏹",
    sprite: "🏹",
    image: unitImage("u_archer", "🏹", "#7be2a5"),
    tint: "#7be2a5",
    tier: 1,
    role: "backline",
    hp: 80,
    atk: 20,
    trait: ["ranger", "elf"],
  },
  {
    id: "u_mech",
    name: "齿轮术士",
    icon: "⚙️",
    sprite: "⚙️",
    image: unitImage("u_mech", "⚙️", "#f6d56f"),
    tint: "#f6d56f",
    tier: 2,
    role: "backline",
    hp: 95,
    atk: 22,
    trait: ["engineer", "machine"],
  },
  {
    id: "u_monk",
    name: "灰烬武僧",
    icon: "🥋",
    sprite: "🥋",
    image: unitImage("u_monk", "🥋", "#ff9d7a"),
    tint: "#ff9d7a",
    tier: 2,
    role: "midline",
    hp: 110,
    atk: 18,
    trait: ["fighter", "human"],
  },
  {
    id: "u_mage",
    name: "虚空术师",
    icon: "🔮",
    sprite: "🔮",
    image: unitImage("u_mage", "🔮", "#ca95ff"),
    tint: "#ca95ff",
    tier: 3,
    role: "backline",
    hp: 88,
    atk: 30,
    trait: ["mage", "void"],
  },
  {
    id: "u_knight",
    name: "暮色骑士",
    icon: "🗡️",
    sprite: "🗡️",
    image: unitImage("u_knight", "🗡️", "#8dd1ff"),
    tint: "#8dd1ff",
    tier: 3,
    role: "frontline",
    hp: 150,
    atk: 24,
    trait: ["sentinel", "night"],
  },
  {
    id: "u_assassin",
    name: "影缝者",
    icon: "🕶️",
    sprite: "🕶️",
    image: unitImage("u_assassin", "🕶️", "#b9c0d5"),
    tint: "#b9c0d5",
    tier: 4,
    role: "backline",
    hp: 90,
    atk: 40,
    trait: ["assassin", "night"],
  },
  {
    id: "u_titan",
    name: "巨像",
    icon: "🧱",
    sprite: "🧱",
    image: unitImage("u_titan", "🧱", "#ffc178"),
    tint: "#ffc178",
    tier: 4,
    role: "frontline",
    hp: 200,
    atk: 21,
    trait: ["machine", "sentinel"],
  },
];

export const TRAIT_BONUS = {
  sentinel: { need: 2, bonus: { hpPct: 0.12 } },
  ranger: { need: 2, bonus: { atkPct: 0.15 } },
  mage: { need: 2, bonus: { atkPct: 0.18 } },
  machine: { need: 2, bonus: { hpPct: 0.1, atkPct: 0.08 } },
  night: { need: 2, bonus: { atkPct: 0.12 } },
  human: { need: 2, bonus: { hpPct: 0.06 } },
};
