export const UNIT_CONFIG = [
  {
    id: "u_guard",
    name: "铁卫",
    icon: "🛡️",
    tier: 1,
    role: "frontline",
    hp: 120,
    atk: 14,
    trait: ["sentinel", "human"],
  },
  {
    id: "u_archer",
    name: "巡林射手",
    icon: "🏹",
    tier: 1,
    role: "backline",
    hp: 80,
    atk: 20,
    trait: ["ranger", "elf"],
  },
  {
    id: "u_mech",
    name: "齿轮术士",
    icon: "⚙️",
    tier: 2,
    role: "backline",
    hp: 95,
    atk: 22,
    trait: ["engineer", "machine"],
  },
  {
    id: "u_monk",
    name: "灰烬武僧",
    icon: "🥋",
    tier: 2,
    role: "midline",
    hp: 110,
    atk: 18,
    trait: ["fighter", "human"],
  },
  {
    id: "u_mage",
    name: "虚空术师",
    icon: "🔮",
    tier: 3,
    role: "backline",
    hp: 88,
    atk: 30,
    trait: ["mage", "void"],
  },
  {
    id: "u_knight",
    name: "暮色骑士",
    icon: "🗡️",
    tier: 3,
    role: "frontline",
    hp: 150,
    atk: 24,
    trait: ["sentinel", "night"],
  },
  {
    id: "u_assassin",
    name: "影缝者",
    icon: "🕶️",
    tier: 4,
    role: "backline",
    hp: 90,
    atk: 40,
    trait: ["assassin", "night"],
  },
  {
    id: "u_titan",
    name: "巨像",
    icon: "🧱",
    tier: 4,
    role: "frontline",
    hp: 200,
    atk: 21,
    trait: ["machine", "sentinel"],
  },
];

export const TRAIT_BONUS = {
  sentinel: { need: 2, bonus: { hpPct: 0.12 } },
  ranger: { need: 2, bonus: { atkPct: 0.15 } },
  mage: { need: 2, bonus: { atkPct: 0.18 } },
  machine: { need: 2, bonus: { hpPct: 0.1, atkPct: 0.08 } },
  night: { need: 2, bonus: { atkPct: 0.12 } },
  human: { need: 2, bonus: { hpPct: 0.06 } },
};
